name: Gravador de Chat do Snopey

on:
  schedule:
    # Executa a cada 15 minutos entre as 14h e 22h (Horário de Brasília)
    - cron: '*/15 17-23 * * *'
    - cron: '*/15 0-1 * * *'
  workflow_dispatch: # Permite ligar o robô manualmente para testar

jobs:
  gravador_de_chat:
    name: Gravador de Chat
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências do Sistema para Renderização
      run: |
        sudo apt-get update
        sudo apt-get install -y libicu-dev libfontconfig1

    - name: Executar Gravador e Gerador de Vídeo
      run: python gravador.py

    - name: Disponibilizar o arquivo de Vídeo MP4 para Download
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: chat-snopey-video
        path: "*.mp4"
