name: Agendador de Chat do Snopey

on:
  schedule:
    # Executa a cada 15 minutos entre as 14h e 22h (Horário de Brasília)
    - cron: '*/15 17-23 * * *'
    - cron: '*/15 0-1 * * *'
  workflow_dispatch: # Permite ligar o robô manualmente para testar

jobs:
  gravador_job:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar ChatDownloader
      run: pip install chatdownloader

    - name: Executar Gravador
      run: python gravador.py

    - name: Disponibilizar o arquivo JSON para Download
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: chat-snopey-json
        path: "*.json"
