name: Gravador de Chat Automatico

on:
  schedule:
    # O robô agora acorda a cada 6 horas para assumir o plantão longo
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  gravar:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar o repositorio
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar o Gravador
      run: |
        pip install chat-downloader

    - name: Capturar ate a live fechar
      run: |
        # O timeout agora é de 6 horas (21600 segundos).
        # Se a live da Sjokz fechar ANTES disso, o programa encerra na mesma hora sozinho!
        python -m chat_downloader https://www.twitch.tv/sjokz --output chat_sjokz.json --timeout 21600 --format json

    - name: Salvar o arquivo no GitHub
      run: |
        git config --global user.name 'Bot do Chat'
        git config --global user.email 'bot@github.com'
        git add chat_sjokz.json
        git commit -m "Chat da Sjokz atualizado apos o fim da live" || exit 0
        git push
